config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path
from website import views

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='paginainicial'),
    path('sobre', views.second_page_view, name='sobre'),
    path('contacto', views.third_page_view, name='contacto'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Cree your views here.
def home_page_view(request):
    return render(request, 'website/paginainicial.html')

def second_page_view(request):
    return render(request, 'website/sobre.html')

def third_page_view(request):
    return render(request, 'website/contacto.html')

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
    		<title>Website</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'website\css\estilo.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
	<body style="background: #a9b7c9">
	    <header class="jumbotron text-center">
            <h1 class="display-4">Projeto Web App Django</h1>
            <p class="lead">Bem vindo ao meu Website!</p>
            <hr>
            <nav>
                <a href="{% url 'website:paginainicial' %}" class="btn btn-info">Página Inicial</a>
                <a href="{% url 'website:sobre' %}" class="btn btn-info">Sobre</a>
                <a href="{% url 'website:contacto' %}" class="btn btn-info">Entre em Contacto</a>
            </nav>
        </header>

            <article class="container">
                <main class="col-sm-6">
                    {% block main %}
                    {% endblock main %}
                </main>

                <aside class="col-sm-6">
                    <div">
                        {% load static %}
                        <img id="python_img" src="{% static 'website\images\processo.png' %}" alt="">
                    </div>
                </aside>
            </article>

	    <footer>
            Realizado por: Gonçalo Ferreira 11058519
        </footer>
	</body>
</html>

website/templates/website/contacto.html
{% extends 'website/base.html' %}

{% block main %}
    <form id="form_contacto">
        <div class="form-group">
            <label for="email">Email:</label>
            <input class="form-control" type="text" id="email" placeholder="Insira o seu email">
        </div>

        <div class="form-group">
            <label for="mensagem">Mensagem:</label>
            <textarea class="form-control" id="mensagem" rows="3"></textarea>
        </div>

        <div>
            <input class="btn btn-primary" type="submit" value="Salvar">
        </div>
    </form>
{% endblock %}

website/templates/website/paginainicial.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Página Inicial</h3>
    <p>Neste trabalho vamos aprender a utilizar <br> a framework Django!</p>
{% endblock %}

website/templates/website/sobre.html
{% extends 'website/base.html' %}

{% block main %}
    <div>
        <h3>Sobre</h3>
        <p>Django é uma estrutura da web Python de alto nível que incentiva <br> o desenvolvimento rápido e um design limpo e pragmático.</p>
    </div>

    <div id="sobre">
        <p>Vantagens:</p>
        <ol>
            <li>Ridiculamente rápido.</li>
            <li>Segurança</li>
            <li>Fácil aprendizagem</li>
        </ol>
    </div>
{% endblock %}